#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Apply themes in Bspwm

CFG="$HOME/.config"
BSP="$HOME/.config/bspwm"
GEA="$HOME/.config/geany"
XRES="$HOME/.Xresources.d"

## Set Style
set_style () {
	# apply wallpaper
	feh --bg-fill /usr/share/backgrounds/${1}
	
	# apply color-scheme
	cat "$BSP"/themes/${2} > "$XRES"/colors
	
	# set gtk theme, icons and cursor
	if [[ `pidof xsettingsd` ]]; then
		sed -i -e "s|Net/ThemeName .*|Net/ThemeName \"$3\"|g" ${HOME}/.xsettingsd
		sed -i -e "s|Net/IconThemeName .*|Net/IconThemeName \"$4\"|g" ${HOME}/.xsettingsd
		sed -i -e "s|Gtk/CursorThemeName .*|Gtk/CursorThemeName \"$5\"|g" ${HOME}/.xsettingsd
	
		sed -i -e "s/gtk-theme-name=.*/gtk-theme-name=\"$3\"/g" ${HOME}/.gtkrc-2.0
		sed -i -e "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=\"$4\"/g" ${HOME}/.gtkrc-2.0
		sed -i -e "s/gtk-cursor-theme-name=.*/gtk-cursor-theme-name=\"$5\"/g" ${HOME}/.gtkrc-2.0
		
		sed -i -e "s/gtk-theme-name=.*/gtk-theme-name=$3/g" ${CFG}/gtk-3.0/settings.ini
		sed -i -e "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=$4/g" ${CFG}/gtk-3.0/settings.ini
		sed -i -e "s/gtk-cursor-theme-name=.*/gtk-cursor-theme-name=$5/g" ${CFG}/gtk-3.0/settings.ini
	fi
	
	# set default cursor
	sed -i -e "s/Inherits=.*/Inherits=$5/g" ${HOME}/.icons/default/index.theme
	
	# set default gdm3 cursor and gtk theme *REMEMBER TO DELETE "#" FROM '/etc/gdm3/greeter.dconf-defaults'*
	#sed -i -e "s/gtk-theme=.*/gtk-theme=$3/g" /etc/gdm3/greeter.dconf-defaults
	#sed -i -e "s/cursor-theme=.*/cursor-theme=$5/g" /etc/gdm3/greeter.dconf-defaults
	
	# apply geany color-scheme
	sed -i -e  "s/color_scheme=.*/color_scheme=$6/g" ${GEA}/geany.conf
	
	# reload config
	bspc wm -r
}

set_style "${1}" "${2}" "${3}" "${4}" "${5}" "${6}"
