#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations --------------------------------------------#
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII' 'IX'
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' '' ''
		let name++
	done
}
workspaces

bspc config border_width	1
bspc config window_gap		4
bspc config border_radius	6
bspc config split_ratio		0.50

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

# 1 > terminal
bspc rule -a Alacritty desktop='^1' follow=on focus=on
declare -a term=()
for i in ${term[@]}; do
   bspc rule -a $i desktop='^1' state=floating follow=on focus=on; done

# 2 > web
bspc rule -a Firefox-esr desktop='^2' follow=on focus=on
bspc rule -a Chromium desktop='^2' follow=on focus=on
declare -a web=()
for i in ${web[@]}; do
   bspc rule -a $i desktop='^2' state=floating follow=on focus=on; done

# 3 > files
bspc rule -a Org.gnome.Nautilus desktop='^3' follow=on focus=on
declare -a files=()
for i in ${files[@]}; do
   bspc rule -a $i desktop='^3' state=floating follow=on focus=on; done

# 4 > code
bspc rule -a Geany desktop='^4' follow=on focus=on
bspc rule -a VSCodium desktop='^4' follow=on focus=on
declare -a code=()
for i in ${code[@]}; do
   bspc rule -a $i desktop='^4' state=floating follow=on focus=on; done

# 5 > office and docs
bspc rule -a libreoffice-writer desktop='^5' follow=on focus=on
bspc rule -a libreoffice-calc desktop='^5' follow=on focus=on
bspc rule -a libreoffice-impress desktop='^5' follow=on focus=on
bspc rule -a libreoffice-startcenter desktop='^5' follow=on focus=on
bspc rule -a libreoffice Soffice desktop='^5' follow=on focus=on
bspc rule -a *:libreofficedev desktop='^5' follow=on focus=on
bspc rule -a *:soffice desktop='^5' follow=on focus=on
declare -a office=()
for i in ${office[@]}; do
   bspc rule -a $i desktop='^5' state=floating follow=on focus=on; done

# 6 > Communication
bspc rule -a thunderbird desktop='^6' follow=on focus=on
bspc rule -a TelegramDesktop desktop='^6' follow=on focus=on
bspc rule -a whatsdesk desktop='^6' follow=on focus=on
bspc rule -a Hexchat desktop='^6' follow=on focus=on
declare -a comm=()
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^6' state=floating follow=on focus=on; done

# 7 > media
bspc rule -a Inkscape desktop='^7' follow=on focus=on
bspc rule -a Gimp-2.10 desktop='^7' follow=on focus=on
bspc rule -a deemix-gui desktop='^7' follow=on focus=on
declare -a media=(Audacity obs Hypnotix.py)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^7' state=floating follow=on focus=on; done
   
# 8 > games
bspc rule -a valheim desktop='^8' follow=on focus=on
bspc rule -a snowrunner desktop='^8' follow=on focus=on
declare -a games=(discord Steam)
for i in ${games[@]}; do
   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done

# 9 > settings
bspc rule -a 'VirtualBox Manager' desktop='^9' follow=on focus=on
bspc rule -a GParted desktop='^9' follow=on focus=on
bspc rule -a 'Software' desktop='^9' follow=on focus=on
declare -a settings=(Lxappearance Arandr Pavucontrol \
Xfce4-power-manager-settings Exo-helper-1 \
Nm-connection-editor Virt-manager)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^9' state=floating follow=on focus=on; done

# special rules
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off
declare -a floating=(Gnome-calculator Viewnior feh authy Mousepad)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager mpd

# Lauch notification daemon
dunst \
-geom "280x50-10+42" -frame_width "1" -font "Iosevka Custom 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# Lauch xsettingsd daemon
xsettingsd &

# Polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
fi

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash $HOME/.fehbg

# Start mpd
exec mpd &

# Start bspwm scripts
bspcolors
bspbar
bspcomp
bspfloat &
